server:
    port: ${SERVER_PORT}

spring:
    application:
        name: ${SPRING_APPLICATION_NAME}
    
    data:
        mongodb:
            host: ${MONGO_HOST}
            port: ${MONGO_PORT}
            database: ${MONGO_DB}

jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
    
cors:
    allowed_origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    org.springframework.security: DEBUG   # security-related debug
